# Conhecendo o Python

In [6]:

x = 1
y = 2.57
print("x vale ", x)
print("y vale ", y)

x vale  1
y vale  2.57

In [7]:
x+y

3.57

In [9]:
x = "Data " 
y = "Science"

print(x+y)

Data Science

In [10]:
True + True + False

2

In [ ]:
None

## Conhecendo os Tipos

In [11]:
teste = [1,1]
type(teste)

list

In [12]:
int(3.99)

3

## Trabalhando com o pandas

In [3]:
import pandas as pd
import numpy as np

serie = pd.Series([3,7,5,6,"teste",8, np.nan])
serie

0        3
1        7
2        5
3        6
4    teste
5        8
6      NaN
dtype: object

In [4]:
serie.head(3)

0    3
1    7
2    5
dtype: object

In [5]:
serie.tail(2)

5      8
6    NaN
dtype: object

In [6]:
serie.dtype

dtype('O')

In [7]:
serie.isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [8]:
serie[serie.isnull()]

6    NaN
dtype: object

In [9]:
serie.value_counts()

3        1
7        1
5        1
6        1
teste    1
8        1
Name: count, dtype: int64

In [10]:
data_int = pd.date_range("20250101", periods=6, freq="ME")

In [11]:
data_br = data_int.strftime("%d/%m/%Y")
data_br

Index(['31/01/2025', '28/02/2025', '31/03/2025', '30/04/2025', '31/05/2025',
       '30/06/2025'],
      dtype='object')

In [12]:
df= pd.DataFrame(
    np.random.randint(1,5,size=(6,4)),
    index=data_br,
    columns=["A", "B", "C", "D"])

In [13]:
df.head(3)

            A  B  C  D
31/01/2025  2  2  2  3
28/02/2025  2  1  1  3
31/03/2025  4  4  2  3

In [14]:
df.columns = ['a', 'b', 'c', 'd']

In [15]:
df['Col5'] = pd.Series([1,2,3,4,5,6], index=data_br)

In [16]:
df

            a  b  c  d  Col5
31/01/2025  2  2  2  3     1
28/02/2025  2  1  1  3     2
31/03/2025  4  4  2  3     3
30/04/2025  4  4  1  1     4
31/05/2025  2  2  3  4     5
30/06/2025  2  2  1  3     6

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 31/01/2025 to 30/06/2025
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       6 non-null      int32
 1   b       6 non-null      int32
 2   c       6 non-null      int32
 3   d       6 non-null      int32
 4   Col5    6 non-null      int64
dtypes: int32(4), int64(1)
memory usage: 192.0+ bytes

In [18]:
df.describe()

              a         b         c         d      Col5
count  6.000000  6.000000  6.000000  6.000000  6.000000
mean   2.666667  2.500000  1.666667  2.833333  3.500000
std    1.032796  1.224745  0.816497  0.983192  1.870829
min    2.000000  1.000000  1.000000  1.000000  1.000000
25%    2.000000  2.000000  1.000000  3.000000  2.250000
50%    2.000000  2.000000  1.500000  3.000000  3.500000
75%    3.500000  3.500000  2.000000  3.000000  4.750000
max    4.000000  4.000000  3.000000  4.000000  6.000000

In [19]:
df['Col6'] = pd.Series(['c','b','c','d','e','f'], index=data_br)

In [20]:
df.describe()

              a         b         c         d      Col5
count  6.000000  6.000000  6.000000  6.000000  6.000000
mean   2.666667  2.500000  1.666667  2.833333  3.500000
std    1.032796  1.224745  0.816497  0.983192  1.870829
min    2.000000  1.000000  1.000000  1.000000  1.000000
25%    2.000000  2.000000  1.000000  3.000000  2.250000
50%    2.000000  2.000000  1.500000  3.000000  3.500000
75%    3.500000  3.500000  2.000000  3.000000  4.750000
max    4.000000  4.000000  3.000000  4.000000  6.000000

In [21]:
df.describe(include="O")

       Col6
count     6
unique    5
top       c
freq      2